MessDeck/MessDeck/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('mess_student.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MessDeck/mess_student/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import datetime
from django.utils import timezone
# Create your models here.
hostel=(


    ("SR Mess","SR"),
    ("MEERA Mess","MEERA"),
    ("KG Mess","KRISHNA"),
    ("KG Mess","GANDHI"),
    ("RVA Mess","RANAPRATAP"),
    ("RVA Mess","ASHOK"),
    ("RVA Mess","VISHWAKARMA"),
    ("RB Mess","RAM"),
    ("RB Mess","BUDH"),
    ("MALVIYA Mess","MALVIYA"),
    ("CV Mess","CV"),
    ("SV Mess","SHANKAR"),
    ("SHANKAR Mess","VYAS")



)


class Student_Profile(models.Model):    
    suser=models.OneToOneField(User,on_delete=models.CASCADE)
    bits_id=models.CharField(max_length=13,default="")
    student_hostel=models.CharField(max_length=20,choices=hostel,default="SR Mess")

    def __str__(self) :
        return f' {self.suser.first_name}   {self.bits_id}   {self.student_hostel}'
    
    
class Mess_Profile(models.Model):    
    muser=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    
    psrn_no=models.CharField(max_length=10,default="")
    def __str__(self) :
        return f' {self.muser.username}   {self.psrn_no}'
    
class Day_Menu(models.Model):
    day=models.DateField()
    def __str__(self):
        return f'Menu of {self.day}'

    
class Meal(models.Model):
    meal=models.CharField(max_length=10)
    of_day=models.ForeignKey(Day_Menu,on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.meal} of {self.of_day}'
    
class Item(models.Model):
    item_name=models.CharField(max_length=20)
    item_in=models.ForeignKey(Meal,on_delete=models.CASCADE)
    #item_rating=models.ManyToManyField(User)
    #item_rating_value=models.PositiveIntegerField(default=0,max_length=1)
    item_avg_rating=models.DecimalField(max_digits=3,decimal_places=1,default=0)
    
    def __str__(self):
        return f'{self.item_name}  {self.item_avg_rating}'
class Ratings(models.Model):
      item=models.ForeignKey(Item,on_delete=models.CASCADE)
      users=models.ForeignKey(User,on_delete=models.CASCADE)
      rating=models.PositiveIntegerField(default=5)
      #avg_rating=models.DecimalField(max_digits=2,decimal_places=1,default=0)
      def __str__(self):
          return f'{self.item.item_name} of {self.item.item_in.of_day.day} '
      

class Review(models.Model):
    format = '%d-%b-%y'
    title=models.CharField(max_length=20)
    description=models.TextField()
    image=models.ImageField(upload_to='review_pics/',null=True,blank=True)
    by=models.ForeignKey(User,on_delete=models.CASCADE)
    on=models.DateTimeField(default=timezone.now)
    #date=models.DateField(default=datetime.datetime.date(format))
    def __str__(self):
        return f'{self.title}'
    def get_absolute_url(self):
        return reverse('menu')
class MenuFile(models.Model):
    file=models.FileField(upload_to='menu/')
    def __str__(self):
        return f'{self.file.name}'
    def get_absolute_url(self):
        return reverse('menu')

class Bill(models.Model):
    student=models.OneToOneField(User,on_delete=models.CASCADE)
    breakfast_attended=models.PositiveIntegerField(default=0)
    dinner_attended=models.PositiveIntegerField(default=0)
    lunch_attended=models.PositiveIntegerField(default=0)
    billtotal=models.PositiveIntegerField(default=0)
    def __str__(self):
        return f'{self.student} Bill  {self.billtotal}'
    
    
    

class Meal_attendees(models.Model):
    meal=models.OneToOneField(Meal,on_delete=models.CASCADE)
    no_attended=models.PositiveIntegerField(default=0)
    def __str__(self):
        return f'{self.meal.meal} of {self.meal.of_day.day} {self.no_attended}'
    
   

MessDeck/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<title>MessDeck</title>
</head><body style="background-color: black;">
	<nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding-left:1%;">
		<div class="container-fluid">
		  <a class="navbar-brand" href="{% url 'home' %}" style="font-size:xx-large; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">MessDeck</a>
		  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
			  		<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'profile' %}">Profile</a>
			  		</li>
			  
			  		<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{% url 'viewmenu' %}">Month's Menu</a>
			  		</li>
			  		{%if user.student_profile %}
				<li class="nav-item">
					
						<a class="nav-link active" aria-current="page" href="{% url 'createreview' %}">Write Review</a>
						{%elif user.mess_profile %}
						<a class="nav-link active" aria-current="page" href="{% url 'reviewlist' %}">Reviews</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'upload-excel' %}">Change Menu</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'attendance' %}">Attendance</a>
					</li>
					
					

					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'bill_list' %}">Bills</a>
					</li>{%endif%}

				
				<li class="nav-item">
						{% if user.is_authenticated %}
							<a class="nav-link" href="{% url 'LogoutPage' %}">Logout</a>
						{%else%}
							<a class="nav-link" href="{% url 'home' %}">Login</a>
						{%endif%}
					
				</li>
				</ul>
		  </div>	
			
	    </div>
	
	  </nav>
	  {%if messages%}
	  {%for message in messages%}
	 <div style="text-align: center; border: solid blue; background-color: red; border-radius: 400px;">{{message}}</div>
	 {%endfor%}
	 {%endif%}
	{% block content %}
    {% endblock %}
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  
</body>
</html>

MessDeck/templates/createprofile.html

{%extends "base.html"%}
{%block content%}


<legend style="align-self: center;">
    <div class="content-section" style="background-color: blue;">
            <fieldset style="text-align: center; margin: 2 auto; border: red;">
                <form method="post">
                    {%csrf_token%}
            
                 {{form.as_p}}
            
            
            
                
                
            </fieldset>
            <div style="text-align: center;" ><button type="submit">Set</button><br></form></div>
             
            </div>
        </div></legend>
        {% endblock %}

MessDeck/templates/home.html
{%extends "base.html"%}
{% load socialaccount %}
{% block content%}
{% if user.is_authenticated %}
  
  

      
 
<br><br><br><br><br><br><br>
{% if menudaylist%}
<h1 class="text-center" id="xxx-large" style="color: lawngreen;" >Menu of current month</h1>
<br><br><br>

  <div class="container" style="color: white;">
    <div class="row">
      {%for menuday in menudaylist%}
        <div class="col-md-4">
          <!-- Display item information -->
          <h3><a href="{%url 'viewmenudetail' menuday.id%}">{{ menuday.day }}</a></h3>
          
        </div>
      {% endfor %}
    </div>
  </div>{%endif%}
 
    
  
<form action="{% url 'mark_attendance' %}" method="post">
  {% csrf_token %}
{%if user.student_profile%}
  
  <div style="text-align: center;"><button type="submit" value="submit"class="btn btn-primary">MARK ATTENDANCE</button></div>
 {%endif%}

</form>
{%if next_meal%}
<div style="text-align: center;"><h1>NEXT MEAL</h1>
<h2 style="color: blue;">{{ next_meal.meal }}</h2>
    {% for i in next_meal.item_set.all %}
      <h3 style="color: lawngreen;">{{ i.item_name }}</h3>
     {%endfor%}</div>{%endif%}
 {%if attend_list %}
 <h1 style="text-align: center;color: green;">ATTENDANCE</h1>
<div class="row" style="text-align: center ;color: white;font-size: larger;">
    <div class="col">MEAL</div>
    <div class="col">DATE</div>
    <div class="col">Attended by</div></div>
    
    <div class="w-100"></div>
    {%for attend in attend_list%}
    <div class="row" style="text-align: center;color: white;border: solid; font-size: large;">
      <div class="col">{{attend.meal.meal}} </div>
      <div class="col">{{attend.meal.of_day.day}}</div>
      <div class="col" style="text-align: center;">{{attend.no_attended}}</div></div>
      <div class="w-100"></div>
      {%endfor%}
      {%endif%}
    
 




  
 

    
    
    
  

{% else %}
<br><br><br><br><br><br><br>
<h1 class="text-center" id="xxx-large" style="color: lawngreen;" >WELCOME TO MessDeck</h1>
<br><br><br>

<div class="container">
  <div class="row justify-content-center" style="padding: 0%; margin: 0;">
    <div class="col-4" style="border:solid; color:red;">
     <div style="border: SOLID; color: red; font-size: xx-large; display:block; text-align: center;">STAFF LOGIN</div><br><br><br>
     <h3 style="text-align: center;"><a href="{%url 'LoginPage' %}"><button>Login</button></a></h3>
  
    </div>
    <div class="col-4" style="border:solid;color:white;height: 300px;">
      <div style="border: SOLID; color: white; font-size: xx-large; display:block; text-align: center;">STUDENT LOGIN</div>

      <figure class="text-center" >
        <blockquote class="blockquote">
    
    

        <p><h1>Login with Gmail</h1></p>
        </blockquote>
        <figcaption >
           <a href="{% provider_login_url 'google' %}" ><button class="btn-"><h1>Login</h1></button</a> 
        </figcaption>
      </figure>
    
      
    </div>
  </div>
</div>
{% endif %}
{% endblock %}





MessDeck/templates/login.html
{%extends "base.html"%}
{%block content%}
<legend style="align-self: center;">
    <div class="content-section" style="background-color: blue;">
            <fieldset style="text-align: center; margin: 2 auto; border: red;">
                <form method="post">
                    {%csrf_token%}
            
                 {{form.as_p}}
            </fieldset>
            <div style="text-align: center;" ><button type="submit">Login</button><br></form></div>
        </div>
    </div></legend>
    {% endblock content %}
             
            
            
            
                
                

MessDeck/templates/logout.html
{%extends "base.html"%}
{%block content%}

<h2 style="text-align: center; color: white;" >You have been logged out!!</h2>
   
<h3 style="text-align: center;" >>Want to login? <a href="{% url 'home' %}" style="font-weight: 600;"> Login</a></h3>
{% endblock %}

        
            


MessDeck/templates/menudetail.html
{%extends "base.html"%}

{% block content %}
  <div class="container"> 
   <form action="{%url 'rate' day.pk %}"method="post"> {%csrf_token%}
    <div class="row">
        <h1 style="text-align: center; color: chartreuse;">MENU OF {{  day.day}}</h1>
    {% for m in day.meal_set.all %}
    <div class="col-md-4 mb-4">
      <h2 style="color: blue;">{{ m.meal }}</h2>
      {% for i in m.item_set.all %}
        <h3 style="color: lawngreen;">{{ i.item_name }}</h3>
        {%if user.student_profile %}
     <input type="range" class="form-control-range" id="slider" name="slider{{i.pk}}" min="0" max="10" step="1">
      {%endif%}
      {%if user.mess_profile %}
      <h4 style="color: white;">Average rating:{{ i.item_avg_rating }}</h4>
      {%endif%}
      
          
      {%endfor%}</div>
      
    {% endfor %}</div>{%if user.student_profile %}<div style="text-align: center;"><button type="submit" value="submit" name="ratingbutton"class="btn btn-primary">Rate items in {{day}}</button></div>
    {%endif%}
</form>
<br><br><br>
{%if user.mess_profile %}
<div style="text-align: center;"><a href="{%url 'avgrate' day.id %}"><button type="submit" value="submit" name="ratingbutton"class="btn btn-primary">Update Average rating of items in {{day}}</button></a></div>
{%endif%}
</div> <br> <br>

{% endblock %}

MessDeck/templates/profile.html
{%extends "base.html"%}
{%block content%}
{% if checker %}
<div class="container">
    <h1 class="text-success">{{request.user}}'s Profile</h1>
    <div class="card">
        <div class="card-header">PSRN NO.:{{request.user.mess_profile.psrn_no}}</div>
        <div class="card-header">DESIGNATION:MESS STAFF</div>
    </div>
   
</div>
{% else %}
<div class="container">
    <h1 class="text-success">{{request.user.first_name}}'s Profile</h1>
    <div class="card">
        <div class="card-header">Bits ID: {{request.user.student_profile.bits_id}}</div>
        <div class="card-body">Mess: {{request.user.student_profile.student_hostel}} </div>
        
    </div>
    
</div>

{% endif %}
<div class="card-body" style="text-align: center; font-size: larger;"><a href="{%url 'createprofile'%}"  style="display: inline-block;"> Edit Profile</a></div>


{% endblock %}

MessDeck/templates/review.html
{%extends "base.html"%}
{%block content%}
 {%if user.mess_profile%}
    {%for review in reviewlist%}
    <div class="row mb-2" >
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
         
          <h3 class="mb-0" style="color: white;">{{review.title}}</h3>
          <div class="mb-1 text-muted">{{review.on}}</div>
          <p class="card-text mb-auto"style="color: white;">{{review.description}}</p>
          <div class="mb-1 text-muted">By:{{review.by.first_name}} {{review.by.last_name}}</div>
        </div>
        <div class="col-auto d-none d-lg-block">
           {%if review.image%}
          <img src="{{review.image.url}}" alt="" width="400%" height="250%"></svg>
            {%endif%}
        </div>
      </div>
    </div>
      {%endfor%}
   {%endif%}
    
      
    
  </div>
  {%endblock%}

MessDeck/templates/reviewform.html
{%extends "base.html"%}
{% block content%}
<legend style="align-self: center; text-align: center;">
    <h1 style="text-align: center; margin: 2 auto; color: red; ">Write Review</h1>
    <div class="content-section" style="background-color:white; display: inline-block; text-align: center;">
            <fieldset style="text-align: center; margin: 2 auto; border: red;">
                <form method="post" enctype="multipart/form-data">
                    {%csrf_token%}
            
                 {{form.as_p}}
            </fieldset>
            <div style="text-align: center;" ><button type="submit">SUBMIT</button><br></form></div>
            </div>
        </div></legend>
        {%endblock%}
             
            
            
                
                
            
                
                



MessDeck/templates/student_bills.html
{%extends "base.html"%}
{% block content%}
{%if user.mess_profile %}
<h1 style="text-align: center;color: green;">BILL LIST</h1>
<div class="row" style="text-align: center ;color: white;border: solid;font-size: larger;">
    <div class="col">STUDENT NAME</div>
    <div class="col">BREAKFASTS ATTENDED</div>
    <div class="col">LUNCHS ATTENDED</div>
    <div class="col">DINNERS ATTENDED</div>
    <div class="col">TOTAL BILL</div>
    <div class="col">Convert to excel</div>
</div>

    <div class="w-100"></div>
    {%for bill in bill_set%}
    <div class="row" style="text-align: center;color: white;border: solid; font-size: large;">
        <div class="col">{{bill.student.first_name}} {{ bill.student.last_name}}</div>
        <div class="col">{{bill.breakfast_attended}}</div>
        <div class="col">{{bill.lunch_attended}}</div>
        <div class="col">{{bill.dinner_attended}}</div>
        <div class="col">{{bill.billtotal}}</div>
    <div class="col"><a href="{%url 'convert_to_excel' bill.pk %}" ><button class="btn btn-info">Import to Excel</button></a></form></div>
</div>

        <div class="w-100"></div>
        {%endfor%}
        
        
        {%else%}
<h1 style="text-align: center;color: red;">ACCESS DENIED</h1>
            
            
            {%endif%}
{%endblock%}




    

MessDeck/templates/upload_menu.html
{%extends "base.html"%}
{% block content %}
{%if user.mess_profile %}
<div class="form-class" style="text-align: center; background-color: blue;display:block; border: solid;">  
<h2 style="color: lawngreen;">Change Menu </h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn-primary">Change</button>
    </form></div>  
    
    {%else%}
    <h1 style="text-align: center; color: red;">PERMISSION DENIED!</h1>
    {%endif%}
{% endblock %}